name: "csteach402"
subname: "DH Design and Programming"
description: "a collection of resources for COMP 402..."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: "/:categories/:title"
highlighter: pygments

excerpt_separator: <!--more-->

collections:
  library:
    output: true
  indices:
    output: true

gems:
  - jekyll-sitemap
